name: Debricked scan

on: [push]    

jobs:
  debricked:
    runs-on: ubuntu-latest

    container:
      image: debricked/cli:latest-resolution-debian

    steps:    
     - uses: actions/checkout@v4
     - uses: debricked/actions/callgraph@v4
     - run: |
          ls
     - uses: debricked/actions@v4
       env:
          DEBRICKED_TOKEN: '32cab62f9e6f255ac0f7c38cf69c91131276ad0c0fd3fbe6'
          DEBRICKED_URI: 'https://review-6831-reach-qc4gm9.review.debricked.dev'
